name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  cache-path: |
    .git/modules
  CCACHE_DIR: ${{ github.workspace}}/ccache
  CCACHE_DEPEND: true
jobs:
  cache:
    name: Update Submodule Cache
    runs-on: ubuntu-24.04
    outputs:
      key: submodules-${{ steps.submodule-hash.outputs.HASH }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Submodule Hash
        id: submodule-hash
        run: echo "HASH=$(git submodule | sha1sum | head -c 40)" >> $GITHUB_OUTPUT

      - name: Check if Cache Exists for Exact Submodule Configuration
        id: cache-check
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.cache-path }}
          key: submodules-${{ steps.submodule-hash.outputs.HASH }}
          lookup-only: true

      - name: If Cache Misses, Update Cache
        uses: actions/cache@v4
        if: steps.cache-check.outputs.cache-hit != 'true'
        with:
          path: ${{ env.cache-path }}
          key: submodules-${{ steps.submodule-hash.outputs.HASH }}
          restore-keys: |
            submodules-

      - name: Clone Submodules
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: |
          git submodule update --init --progress uclibc-ng
          git submodule update --init --progress --depth 1 --jobs $(nproc)


    
  build:
    name: Build Toolchain Variants
    runs-on: ${{ matrix.os }}
    needs: [cache]
    env:
      cache-key: ${{ needs.cache.outputs.key }}
      INSTALL_DIR: ${{ github.workspace }}/riscv
    strategy:
      matrix:
        os:     [ubuntu-22.04, ubuntu-24.04]
        mode:   [newlib, linux, musl, uclibc]
        target: [rv32gc-ilp32d, rv64gc-lp64d]
        compiler: [gcc, llvm]
        exclude:
          - mode: musl
            compiler: llvm
          - mode: uclibc
            compiler: llvm
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: '10240'

      - name: Generate Prebuilt Toolchain Name
        id:   toolchain-name-generator
        run: |
          if [[ "${{ matrix.target }}" == *"32"* ]]; then BITS=32; else BITS=64; fi
          case "${{ matrix.mode }}" in
            "linux")
              MODE="glibc";;
            "musl")
              MODE="musl";;
            "uclibc")
              MODE="uclibc-ng";;
            *)
              MODE="elf";;
          esac
          echo "TOOLCHAIN_NAME=riscv$BITS-$MODE-${{ matrix.os }}-${{ matrix.compiler }}-nightly" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Load Submodule Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.cache-path }}
          key: ${{ env.cache-key }}

      - name: Install Dependencies
        run: |
          sudo ./.github/setup-apt.sh
          sudo apt-get install -y --no-install-recommends ccache
          ln -s $(command -v ccache) /usr/local/bin/gcc
          ln -s $(command -v ccache) /usr/local/bin/g++
          ln -s $(command -v ccache) /usr/local/bin/cc
          ln -s $(command -v ccache) /usr/local/bin/c++

      - name: Load Compile Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache
        
      - name: Build Toolchain         
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          BUILD_TOOLCHAIN="./configure --prefix=${{ env.INSTALL_DIR }} --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]}"
          if [ "${{ matrix.compiler }}" == "llvm" ]; then # build toolchain with llvm
            $BUILD_TOOLCHAIN --enable-llvm
          else
            $BUILD_TOOLCHAIN
          fi
          make -j $(nproc) ${{ matrix.mode }}

      - name: Cache Stats
        if: ${{ always() }}
        run: |
          ls -la ${{ env.CCACHE_DIR }}
          cd ${{ env.CCACHE_DIR }}
          ccache -s
          ccache -x
          du -h -d 1

      - name: Save Compile Cache
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ccache-${{ steps.toolchain-name-generator.outputs.TOOLCHAIN_NAME }}
          path: ${{ env.CCACHE_DIR }}
          include-hidden-files: true

      - name: Tar Toolchain
        if: false
        run: tar czvf riscv.tar.gz -C ${{ github.workspace }} riscv/

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: ${{ steps.toolchain-name-generator.outputs.TOOLCHAIN_NAME }}
          path: riscv.tar.gz

  ccache:
    name: Post-Process CCache Data
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ccache-riscv*
          path: ${{ env.CCACHE_DIR }}
          merge-multiple: true
      
      - name: Cleanup ccache
        run: |
          sudo apt-get install ccache
          ccache -s
          ccache -x
          ccache -c
          ccache -s
          ccache -x

      - name: Commit CCache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache

  test-sim:
    name: Test Simulation
    runs-on: ${{ matrix.os }}
    needs: [cache]
    env:
      cache-key: ${{ needs.cache.outputs.key }}
    strategy:
      matrix:
        os:     [ubuntu-24.04]
        mode:   [newlib]
        target: [rv64gc-lp64d]
        sim:    [spike]
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v4

      - name: Restore Submodule Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.cache-path }}
          key: ${{ env.cache-key }}

      - name: Install Dependencies
        run: sudo ./.github/setup-apt.sh

      - name: Build Toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          ./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]} --with-sim=${{ matrix.sim }}
          make -j $(nproc) ${{ matrix.mode }}

      - name: Generate Report
        run: make report-${{ matrix.mode }} -j $(nproc)

  build-multilib:
    if: ${{ false }} # Disable until multilib errors are triaged
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:     [ubuntu-24.04]
        mode:   [newlib, linux]
        target: [rv64gc-lp64d]
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: build toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          ./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]} --enable-multilib
          sudo make -j $(nproc) ${{ matrix.mode }}

      - name: make report
        run: |
          sudo make report-${{ matrix.mode }} -j $(nproc)

      - name: tarball build
        run: tar czvf riscv.tar.gz -C /opt/ riscv/

      - name: generate prebuilt toolchain name
        id:   toolchain-name-generator
        run: |
          if [[ "${{ matrix.target }}" == *"32"* ]]; then BITS=32; else BITS=64; fi
          case "${{ matrix.mode }}" in
            "linux")
              MODE="glibc";;
            "musl")
              MODE="musl";;
            "uclibc")
              MODE="uclibc-ng";;
            *)
              MODE="elf";;
          esac
          echo "TOOLCHAIN_NAME=riscv$BITS-$MODE-${{ matrix.os }}-multilib-nightly" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.toolchain-name-generator.outputs.TOOLCHAIN_NAME }}
          path: riscv.tar.gz
