on:
  push:
    branches:
    - master
    paths:
    - '.devcontainer/**'

jobs:
  build:
    name: Build Devcontainer
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      run: |
        sudo apt-get install -y --no-install-recommends npm
        npm install -g @devcontainers/cli
        devcontainer build --workspace-folder . --image-name ghcr.io/tshapinsky/riscv-gnu-toolchain/devcontainer --platform linux/amd64,linux/arm64 --push